/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EBatcher7984Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_BATCH_SIZE"
      | "batchSendTokenDifferentAmounts"
      | "batchSendTokenSameAmount"
      | "changeMaxBatchSize"
      | "confidentialProtocolId"
      | "owner"
      | "renounceOwnership"
      | "tokenRescue"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchTokenTransfer"
      | "NewMaxBatchSize"
      | "OwnershipTransferred"
      | "TokenRescued"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_BATCH_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "batchSendTokenDifferentAmounts",
    values: [AddressLike, AddressLike[], BytesLike[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchSendTokenSameAmount",
    values: [AddressLike, AddressLike[], BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "changeMaxBatchSize",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenRescue",
    values: [AddressLike, AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_BATCH_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchSendTokenDifferentAmounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchSendTokenSameAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeMaxBatchSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenRescue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace BatchTokenTransferEvent {
  export type InputTuple = [arg0: AddressLike, recipients: AddressLike[]];
  export type OutputTuple = [arg0: string, recipients: string[]];
  export interface OutputObject {
    arg0: string;
    recipients: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewMaxBatchSizeEvent {
  export type InputTuple = [size: BigNumberish];
  export type OutputTuple = [size: bigint];
  export interface OutputObject {
    size: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenRescuedEvent {
  export type InputTuple = [token: AddressLike, recipient: AddressLike];
  export type OutputTuple = [token: string, recipient: string];
  export interface OutputObject {
    token: string;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EBatcher7984 extends BaseContract {
  connect(runner?: ContractRunner | null): EBatcher7984;
  waitForDeployment(): Promise<this>;

  interface: EBatcher7984Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_BATCH_SIZE: TypedContractMethod<[], [bigint], "view">;

  batchSendTokenDifferentAmounts: TypedContractMethod<
    [
      token: AddressLike,
      recipients: AddressLike[],
      amounts: BytesLike[],
      inputProof: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  batchSendTokenSameAmount: TypedContractMethod<
    [
      token: AddressLike,
      recipients: AddressLike[],
      amountPerRecipient: BytesLike,
      inputProof: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  changeMaxBatchSize: TypedContractMethod<
    [size: BigNumberish],
    [void],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  tokenRescue: TypedContractMethod<
    [
      token: AddressLike,
      to: AddressLike,
      amount: BytesLike,
      inputProof: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_BATCH_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "batchSendTokenDifferentAmounts"
  ): TypedContractMethod<
    [
      token: AddressLike,
      recipients: AddressLike[],
      amounts: BytesLike[],
      inputProof: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchSendTokenSameAmount"
  ): TypedContractMethod<
    [
      token: AddressLike,
      recipients: AddressLike[],
      amountPerRecipient: BytesLike,
      inputProof: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "changeMaxBatchSize"
  ): TypedContractMethod<[size: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tokenRescue"
  ): TypedContractMethod<
    [
      token: AddressLike,
      to: AddressLike,
      amount: BytesLike,
      inputProof: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "BatchTokenTransfer"
  ): TypedContractEvent<
    BatchTokenTransferEvent.InputTuple,
    BatchTokenTransferEvent.OutputTuple,
    BatchTokenTransferEvent.OutputObject
  >;
  getEvent(
    key: "NewMaxBatchSize"
  ): TypedContractEvent<
    NewMaxBatchSizeEvent.InputTuple,
    NewMaxBatchSizeEvent.OutputTuple,
    NewMaxBatchSizeEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TokenRescued"
  ): TypedContractEvent<
    TokenRescuedEvent.InputTuple,
    TokenRescuedEvent.OutputTuple,
    TokenRescuedEvent.OutputObject
  >;

  filters: {
    "BatchTokenTransfer(address,address[])": TypedContractEvent<
      BatchTokenTransferEvent.InputTuple,
      BatchTokenTransferEvent.OutputTuple,
      BatchTokenTransferEvent.OutputObject
    >;
    BatchTokenTransfer: TypedContractEvent<
      BatchTokenTransferEvent.InputTuple,
      BatchTokenTransferEvent.OutputTuple,
      BatchTokenTransferEvent.OutputObject
    >;

    "NewMaxBatchSize(uint16)": TypedContractEvent<
      NewMaxBatchSizeEvent.InputTuple,
      NewMaxBatchSizeEvent.OutputTuple,
      NewMaxBatchSizeEvent.OutputObject
    >;
    NewMaxBatchSize: TypedContractEvent<
      NewMaxBatchSizeEvent.InputTuple,
      NewMaxBatchSizeEvent.OutputTuple,
      NewMaxBatchSizeEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TokenRescued(address,address)": TypedContractEvent<
      TokenRescuedEvent.InputTuple,
      TokenRescuedEvent.OutputTuple,
      TokenRescuedEvent.OutputObject
    >;
    TokenRescued: TypedContractEvent<
      TokenRescuedEvent.InputTuple,
      TokenRescuedEvent.OutputTuple,
      TokenRescuedEvent.OutputObject
    >;
  };
}
