/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EWETHInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "completeWithdrawal"
      | "confidentialBalanceOf"
      | "confidentialProtocolId"
      | "confidentialTotalSupply"
      | "confidentialTransfer(address,bytes32,bytes)"
      | "confidentialTransfer(address,bytes32)"
      | "confidentialTransferAndCall(address,bytes32,bytes)"
      | "confidentialTransferAndCall(address,bytes32,bytes,bytes)"
      | "confidentialTransferFrom(address,address,bytes32,bytes)"
      | "confidentialTransferFrom(address,address,bytes32)"
      | "confidentialTransferFromAndCall(address,address,bytes32,bytes,bytes)"
      | "confidentialTransferFromAndCall(address,address,bytes32,bytes)"
      | "contractURI"
      | "decimals"
      | "deposit"
      | "discloseEncryptedAmount"
      | "isOperator"
      | "makeBalancePubliclyDecryptable"
      | "name"
      | "requestDiscloseEncryptedAmount"
      | "setOperator"
      | "supportsInterface"
      | "symbol"
      | "withdraw"
      | "withdrawalRequests"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AmountDiscloseRequested"
      | "AmountDisclosed"
      | "ConfidentialTransfer"
      | "Deposit"
      | "OperatorSet"
      | "PublicDecryptionVerified"
      | "Withdrawal"
      | "WithdrawalRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "completeWithdrawal",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialBalanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialTotalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialTransfer(address,bytes32,bytes)",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialTransfer(address,bytes32)",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialTransferAndCall(address,bytes32,bytes)",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialTransferAndCall(address,bytes32,bytes,bytes)",
    values: [AddressLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialTransferFrom(address,address,bytes32,bytes)",
    values: [AddressLike, AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialTransferFrom(address,address,bytes32)",
    values: [AddressLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialTransferFromAndCall(address,address,bytes32,bytes,bytes)",
    values: [AddressLike, AddressLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialTransferFromAndCall(address,address,bytes32,bytes)",
    values: [AddressLike, AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "contractURI",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "discloseEncryptedAmount",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isOperator",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "makeBalancePubliclyDecryptable",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "requestDiscloseEncryptedAmount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setOperator",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawalRequests",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "completeWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialBalanceOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialTotalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialTransfer(address,bytes32,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialTransfer(address,bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialTransferAndCall(address,bytes32,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialTransferAndCall(address,bytes32,bytes,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialTransferFrom(address,address,bytes32,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialTransferFrom(address,address,bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialTransferFromAndCall(address,address,bytes32,bytes,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialTransferFromAndCall(address,address,bytes32,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contractURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "discloseEncryptedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isOperator", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "makeBalancePubliclyDecryptable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestDiscloseEncryptedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalRequests",
    data: BytesLike
  ): Result;
}

export namespace AmountDiscloseRequestedEvent {
  export type InputTuple = [encryptedAmount: BytesLike, requester: AddressLike];
  export type OutputTuple = [encryptedAmount: string, requester: string];
  export interface OutputObject {
    encryptedAmount: string;
    requester: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AmountDisclosedEvent {
  export type InputTuple = [encryptedAmount: BytesLike, amount: BigNumberish];
  export type OutputTuple = [encryptedAmount: string, amount: bigint];
  export interface OutputObject {
    encryptedAmount: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConfidentialTransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    amount: BytesLike
  ];
  export type OutputTuple = [from: string, to: string, amount: string];
  export interface OutputObject {
    from: string;
    to: string;
    amount: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositEvent {
  export type InputTuple = [dest: AddressLike, amount: BigNumberish];
  export type OutputTuple = [dest: string, amount: bigint];
  export interface OutputObject {
    dest: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperatorSetEvent {
  export type InputTuple = [
    holder: AddressLike,
    operator: AddressLike,
    until: BigNumberish
  ];
  export type OutputTuple = [holder: string, operator: string, until: bigint];
  export interface OutputObject {
    holder: string;
    operator: string;
    until: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PublicDecryptionVerifiedEvent {
  export type InputTuple = [
    handlesList: BytesLike[],
    abiEncodedCleartexts: BytesLike
  ];
  export type OutputTuple = [
    handlesList: string[],
    abiEncodedCleartexts: string
  ];
  export interface OutputObject {
    handlesList: string[];
    abiEncodedCleartexts: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalEvent {
  export type InputTuple = [source: AddressLike, amount: BytesLike];
  export type OutputTuple = [source: string, amount: string];
  export interface OutputObject {
    source: string;
    amount: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalRequestedEvent {
  export type InputTuple = [source: AddressLike, handle: BytesLike];
  export type OutputTuple = [source: string, handle: string];
  export interface OutputObject {
    source: string;
    handle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EWETH extends BaseContract {
  connect(runner?: ContractRunner | null): EWETH;
  waitForDeployment(): Promise<this>;

  interface: EWETHInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  completeWithdrawal: TypedContractMethod<
    [handle: BytesLike, cleartexts: BytesLike, decryptionProof: BytesLike],
    [void],
    "nonpayable"
  >;

  confidentialBalanceOf: TypedContractMethod<
    [account: AddressLike],
    [string],
    "view"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  confidentialTotalSupply: TypedContractMethod<[], [string], "view">;

  "confidentialTransfer(address,bytes32,bytes)": TypedContractMethod<
    [to: AddressLike, encryptedAmount: BytesLike, inputProof: BytesLike],
    [string],
    "nonpayable"
  >;

  "confidentialTransfer(address,bytes32)": TypedContractMethod<
    [to: AddressLike, amount: BytesLike],
    [string],
    "nonpayable"
  >;

  "confidentialTransferAndCall(address,bytes32,bytes)": TypedContractMethod<
    [to: AddressLike, amount: BytesLike, data: BytesLike],
    [string],
    "nonpayable"
  >;

  "confidentialTransferAndCall(address,bytes32,bytes,bytes)": TypedContractMethod<
    [
      to: AddressLike,
      encryptedAmount: BytesLike,
      inputProof: BytesLike,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  "confidentialTransferFrom(address,address,bytes32,bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      encryptedAmount: BytesLike,
      inputProof: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  "confidentialTransferFrom(address,address,bytes32)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BytesLike],
    [string],
    "nonpayable"
  >;

  "confidentialTransferFromAndCall(address,address,bytes32,bytes,bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      encryptedAmount: BytesLike,
      inputProof: BytesLike,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  "confidentialTransferFromAndCall(address,address,bytes32,bytes)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BytesLike, data: BytesLike],
    [string],
    "nonpayable"
  >;

  contractURI: TypedContractMethod<[], [string], "view">;

  decimals: TypedContractMethod<[], [bigint], "view">;

  deposit: TypedContractMethod<[], [void], "payable">;

  discloseEncryptedAmount: TypedContractMethod<
    [
      encryptedAmount: BytesLike,
      cleartextAmount: BigNumberish,
      decryptionProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  isOperator: TypedContractMethod<
    [holder: AddressLike, spender: AddressLike],
    [boolean],
    "view"
  >;

  makeBalancePubliclyDecryptable: TypedContractMethod<
    [],
    [string],
    "nonpayable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  requestDiscloseEncryptedAmount: TypedContractMethod<
    [encryptedAmount: BytesLike],
    [void],
    "nonpayable"
  >;

  setOperator: TypedContractMethod<
    [operator: AddressLike, until: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  withdraw: TypedContractMethod<
    [amount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  withdrawalRequests: TypedContractMethod<
    [arg0: BytesLike],
    [[string, boolean] & { user: string; isPending: boolean }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "completeWithdrawal"
  ): TypedContractMethod<
    [handle: BytesLike, cleartexts: BytesLike, decryptionProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialBalanceOf"
  ): TypedContractMethod<[account: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "confidentialTotalSupply"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "confidentialTransfer(address,bytes32,bytes)"
  ): TypedContractMethod<
    [to: AddressLike, encryptedAmount: BytesLike, inputProof: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialTransfer(address,bytes32)"
  ): TypedContractMethod<
    [to: AddressLike, amount: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialTransferAndCall(address,bytes32,bytes)"
  ): TypedContractMethod<
    [to: AddressLike, amount: BytesLike, data: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialTransferAndCall(address,bytes32,bytes,bytes)"
  ): TypedContractMethod<
    [
      to: AddressLike,
      encryptedAmount: BytesLike,
      inputProof: BytesLike,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialTransferFrom(address,address,bytes32,bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      encryptedAmount: BytesLike,
      inputProof: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialTransferFrom(address,address,bytes32)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialTransferFromAndCall(address,address,bytes32,bytes,bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      encryptedAmount: BytesLike,
      inputProof: BytesLike,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialTransferFromAndCall(address,address,bytes32,bytes)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BytesLike, data: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "contractURI"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "discloseEncryptedAmount"
  ): TypedContractMethod<
    [
      encryptedAmount: BytesLike,
      cleartextAmount: BigNumberish,
      decryptionProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isOperator"
  ): TypedContractMethod<
    [holder: AddressLike, spender: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "makeBalancePubliclyDecryptable"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "requestDiscloseEncryptedAmount"
  ): TypedContractMethod<[encryptedAmount: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOperator"
  ): TypedContractMethod<
    [operator: AddressLike, until: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [amount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawalRequests"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [[string, boolean] & { user: string; isPending: boolean }],
    "view"
  >;

  getEvent(
    key: "AmountDiscloseRequested"
  ): TypedContractEvent<
    AmountDiscloseRequestedEvent.InputTuple,
    AmountDiscloseRequestedEvent.OutputTuple,
    AmountDiscloseRequestedEvent.OutputObject
  >;
  getEvent(
    key: "AmountDisclosed"
  ): TypedContractEvent<
    AmountDisclosedEvent.InputTuple,
    AmountDisclosedEvent.OutputTuple,
    AmountDisclosedEvent.OutputObject
  >;
  getEvent(
    key: "ConfidentialTransfer"
  ): TypedContractEvent<
    ConfidentialTransferEvent.InputTuple,
    ConfidentialTransferEvent.OutputTuple,
    ConfidentialTransferEvent.OutputObject
  >;
  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "OperatorSet"
  ): TypedContractEvent<
    OperatorSetEvent.InputTuple,
    OperatorSetEvent.OutputTuple,
    OperatorSetEvent.OutputObject
  >;
  getEvent(
    key: "PublicDecryptionVerified"
  ): TypedContractEvent<
    PublicDecryptionVerifiedEvent.InputTuple,
    PublicDecryptionVerifiedEvent.OutputTuple,
    PublicDecryptionVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawal"
  ): TypedContractEvent<
    WithdrawalEvent.InputTuple,
    WithdrawalEvent.OutputTuple,
    WithdrawalEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalRequested"
  ): TypedContractEvent<
    WithdrawalRequestedEvent.InputTuple,
    WithdrawalRequestedEvent.OutputTuple,
    WithdrawalRequestedEvent.OutputObject
  >;

  filters: {
    "AmountDiscloseRequested(bytes32,address)": TypedContractEvent<
      AmountDiscloseRequestedEvent.InputTuple,
      AmountDiscloseRequestedEvent.OutputTuple,
      AmountDiscloseRequestedEvent.OutputObject
    >;
    AmountDiscloseRequested: TypedContractEvent<
      AmountDiscloseRequestedEvent.InputTuple,
      AmountDiscloseRequestedEvent.OutputTuple,
      AmountDiscloseRequestedEvent.OutputObject
    >;

    "AmountDisclosed(bytes32,uint64)": TypedContractEvent<
      AmountDisclosedEvent.InputTuple,
      AmountDisclosedEvent.OutputTuple,
      AmountDisclosedEvent.OutputObject
    >;
    AmountDisclosed: TypedContractEvent<
      AmountDisclosedEvent.InputTuple,
      AmountDisclosedEvent.OutputTuple,
      AmountDisclosedEvent.OutputObject
    >;

    "ConfidentialTransfer(address,address,bytes32)": TypedContractEvent<
      ConfidentialTransferEvent.InputTuple,
      ConfidentialTransferEvent.OutputTuple,
      ConfidentialTransferEvent.OutputObject
    >;
    ConfidentialTransfer: TypedContractEvent<
      ConfidentialTransferEvent.InputTuple,
      ConfidentialTransferEvent.OutputTuple,
      ConfidentialTransferEvent.OutputObject
    >;

    "Deposit(address,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "OperatorSet(address,address,uint48)": TypedContractEvent<
      OperatorSetEvent.InputTuple,
      OperatorSetEvent.OutputTuple,
      OperatorSetEvent.OutputObject
    >;
    OperatorSet: TypedContractEvent<
      OperatorSetEvent.InputTuple,
      OperatorSetEvent.OutputTuple,
      OperatorSetEvent.OutputObject
    >;

    "PublicDecryptionVerified(bytes32[],bytes)": TypedContractEvent<
      PublicDecryptionVerifiedEvent.InputTuple,
      PublicDecryptionVerifiedEvent.OutputTuple,
      PublicDecryptionVerifiedEvent.OutputObject
    >;
    PublicDecryptionVerified: TypedContractEvent<
      PublicDecryptionVerifiedEvent.InputTuple,
      PublicDecryptionVerifiedEvent.OutputTuple,
      PublicDecryptionVerifiedEvent.OutputObject
    >;

    "Withdrawal(address,bytes32)": TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
    Withdrawal: TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;

    "WithdrawalRequested(address,bytes32)": TypedContractEvent<
      WithdrawalRequestedEvent.InputTuple,
      WithdrawalRequestedEvent.OutputTuple,
      WithdrawalRequestedEvent.OutputObject
    >;
    WithdrawalRequested: TypedContractEvent<
      WithdrawalRequestedEvent.InputTuple,
      WithdrawalRequestedEvent.OutputTuple,
      WithdrawalRequestedEvent.OutputObject
    >;
  };
}
