/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as eBatcherUpgradableSol from "./eBatcherUpgradable.sol";
export type { eBatcherUpgradableSol };
export type { EBucks } from "./EBucks";
export type { EWETH } from "./EWETH";
